### ISSUE TITLE
Добавить тесты с проверкой реализаций алгоритмов маскирования/демаскирования симметричных ключей

### ISSUE THREAD

**Issue by george-rudenko** [axelkenzo/libakrypt-0.x#13]
Необходимо добавить тесты с проверкой алгоритмов маскирования/демаркированная симметричных ключей.

Список функций, для которых необходимо написать тесты:
* В файле **ak_magma.c** функции:
  - ak_skey_context_set_mask_additive
  - ak_skey_context_unmask_additive

* В файле **ak_skey.c** функции:
  - ak_skey_context_set_mask_xor
  - ak_skey_context_unmask_xor

Описание тестового набора:
После снятия маски необходимо проверить, что исходный ключ совпадает с демаскированным.

**Comment by axelkenzo** [comment]
Исправлено в ходе тестирования протокольной части библиотеки.
