### ISSUE TITLE
Устранить уязвимость в реализации алгоритма выработки ключей по паролю

### ISSUE THREAD

**Issue by george-rudenko** [axelkenzo/libakrypt-0.x#14]
При использовании функции **ak_bckey_context_set_key_from_password** была обнаружена следующая уязвимость: На вырабатываемый ключ влияет только каждый четвертый символ пароля начиная с первого, т.е 1ый, 5ый, 9ый, ... символы.

Пример кода, иллюстрирующего найденную уязвимость:

```
#include <libakrypt.h>
#include <ak_bckey.h>
#include <wchar.h>

int main()
{
    int error = ak_error_ok;
    struct bckey key_from_pwd = {};
    wchar_t* sample_passwords[] = {
            L"A",
            L"A12",
            L"Abcd",
            L"A321",
            L"BbcdC",
            L"BbcdC12",
            L"BbcdCfgh",
            L"BbcdC321",
            L"DbcdEfghF",
            L"DbcdEfghF12",
            L"DbcdEfghFijk",
            L"DbcdEfghF321",

    };

    wchar_t* sample_salt = L"salt";

    for(int i = 0; i < sizeof(sample_passwords) / sizeof(wchar_t*); i++)
    {
        if ((error = ak_bckey_context_create_kuznechik(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

        if ((error = ak_bckey_context_set_key_from_password(&key_from_pwd, sample_passwords[i],
                                                            wcslen(sample_passwords[i]), sample_salt,
                                                            wcslen(sample_salt))) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

        key_from_pwd.key.unmask(&key_from_pwd.key);

        wprintf(L"for password: %-12ls (length = %2zd) ", sample_passwords[i], wcslen(sample_passwords[i]));
        printf("generated key is: ");
        for (size_t i = 0; i < key_from_pwd.bsize; i++)
        {
            printf("%02X ", *((ak_uint8*)(key_from_pwd.key.key.data + i)));
        }
        printf("\n");

        if ((error = ak_bckey_context_destroy(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }
    }
    return ak_libakrypt_destroy();
}
```

Вывод:
```
[86352] ak_libakrypt_create(): creation of libakrypt is Ok
for password: A            (length =  1) generated key is: D8 57 34 9F 62 42 C8 A2 25 4A 9A C0 94 15 26 DF 
for password: A12          (length =  3) generated key is: D8 57 34 9F 62 42 C8 A2 25 4A 9A C0 94 15 26 DF 
for password: Abcd         (length =  4) generated key is: D8 57 34 9F 62 42 C8 A2 25 4A 9A C0 94 15 26 DF 
for password: A321         (length =  4) generated key is: D8 57 34 9F 62 42 C8 A2 25 4A 9A C0 94 15 26 DF 
for password: BbcdC        (length =  5) generated key is: C0 A8 AC D0 52 59 0D B9 49 29 3E 36 F9 3B 97 0E 
for password: BbcdC12      (length =  7) generated key is: C0 A8 AC D0 52 59 0D B9 49 29 3E 36 F9 3B 97 0E 
for password: BbcdCfgh     (length =  8) generated key is: C0 A8 AC D0 52 59 0D B9 49 29 3E 36 F9 3B 97 0E 
for password: BbcdC321     (length =  8) generated key is: C0 A8 AC D0 52 59 0D B9 49 29 3E 36 F9 3B 97 0E 
for password: DbcdEfghF    (length =  9) generated key is: 11 5C F2 18 A2 C4 C3 B1 88 CB 2C 2A 4A AF 1A E3 
for password: DbcdEfghF12  (length = 11) generated key is: 11 5C F2 18 A2 C4 C3 B1 88 CB 2C 2A 4A AF 1A E3 
for password: DbcdEfghFijk (length = 12) generated key is: 11 5C F2 18 A2 C4 C3 B1 88 CB 2C 2A 4A AF 1A E3 
for password: DbcdEfghF321 (length = 12) generated key is: 11 5C F2 18 A2 C4 C3 B1 88 CB 2C 2A 4A AF 1A E3 
[86352] ak_libakrypt_destroy(): all crypto mechanisms successfully destroyed
```

**Comment by axelkenzo** [comment]
К сожалению, найденная "уязвимость" иллюстрирует некоторое непонимание происходящего.

Я немного исправил код таким образом, чтобы он собирался под msvc10,
потом повторил приведенный результат, и наконец переписал программу без ошибок.
То что получилось, с комментариями, привожу далее

    #include <stdio.h> /* обязательно для использования printf */ 
    #include <libakrypt.h>
    #include <ak_bckey.h>
#include <wchar.h>

int main()
{
    int i = 0; /* определения переменных должны начинаться в начале блока */
    size_t idx = 0;
    int error = ak_error_ok;
   /* инициализация пустой структуры неопределенным инициализатором недопустима для c99
      struct bckey key_from_pwd = {}; */
    struct bckey key_from_pwd;

    wchar_t* sample_passwords[] = {
            L"A",
            L"A12",
            L"Abcd",
            L"A321",
            L"BbcdC",
            L"BbcdC12",
            L"BbcdCfgh",
            L"BbcdC321",
            L"DbcdEfghF",
            L"DbcdEfghF12",
            L"DbcdEfghFijk",
            L"DbcdEfghF321",

    };

    wchar_t* sample_salt = L"salt";

  /* забытая ранее инициализация библиотеки
     (в данном конкретном случае на работу не влияет) */
   if( !ak_libakrypt_create( ak_function_log_stderr )) return ak_libakrypt_destroy();


    for( i = 0; i < sizeof(sample_passwords) / sizeof(wchar_t*); i++)
    {
        if ((error = ak_bckey_context_create_kuznechik(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

      /* основная ошибка заключалась в том, что тип wchar_t занимает два байта в памяти,
         а функция wcslen возвращает количестиво символов в строке,
         а не размер памяти, занимаемый строкой

         нижеприведенный код работает верно, поскольку соответствует тому,
         что ожидает функция выработки ключа.

         резюме:
          1. передавайте в функции именно те параметры, что ожидает функция
             (char *, а не wchar_t* )

          2. используйте для кодировки паролей utf8 кодировку
             (так принято для того, чтобы снять проблемы с многобайтными кодировками)

          3. не используйте Windows )))
      */

        if ((error = ak_bckey_context_set_key_from_password(
               &key_from_pwd,                                       /* контекст ключа */
               sample_passwords[i],  /* указатель на область памяти, где живет пароль */
               wcslen(sample_passwords[i])*sizeof(wchar_t), /* размер памяти в байтах */
               sample_salt,                               /* инициализационный вектор */
               wcslen(sample_salt)*sizeof(wchar_t))         /* длина вектора в байтах */
            ) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

        key_from_pwd.key.unmask(&key_from_pwd.key);

        wprintf(L"for password: %-12ls (length = %2u) ", sample_passwords[i], wcslen(sample_passwords[i]));
        printf("generated key is: ");
        for ( idx = 0; idx < key_from_pwd.bsize; idx++ )
        {
           /* код
               *((ak_uint8*)(key_from_pwd.key.key.data + idx))
              дает неявное приведение к типу ak_pointer */
            printf("%02X ", ((ak_uint8 *)key_from_pwd.key.key.data)[idx] );
        }
        printf("\n");

        if ((error = ak_bckey_context_destroy(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }
    }
    return ak_libakrypt_destroy();
}

**Comment by axelkenzo** [comment]
К сожалению, найденная "уязвимость" иллюстрирует непонимание происходящего.

Я немного исправил код таким образом, чтобы он собирался подо всеми доступными мне версиями msvc, потом повторил результат, приведенный выше,
а потом переписал программу правильно.
Что получилось, привожу ниже.

    #include <stdio.h> /* обязательно для использования printf */
    #include <libakrypt.h>
    #include <ak_bckey.h>
    #include <wchar.h>

    int main()
   {
    int i = 0; /* определения переменных должны начинаться в начале блока */
    size_t idx = 0;
    int error = ak_error_ok;
    /* инициализация пустой структуры неопределенным инициализатором недопустима для c99
        struct bckey key_from_pwd = {}; */
    struct bckey key_from_pwd;

    wchar_t* sample_passwords[] = {
            L"A",
            L"A12",
            L"Abcd",
            L"A321",
            L"BbcdC",
            L"BbcdC12",
            L"BbcdCfgh",
            L"BbcdC321",
            L"DbcdEfghF",
            L"DbcdEfghF12",
            L"DbcdEfghFijk",
            L"DbcdEfghF321",

    };

    wchar_t* sample_salt = L"salt";

    /* забытая ранее инициализация библиотеки
     (в данном конкретном случае на работу не влияет) */
    if( !ak_libakrypt_create( ak_function_log_stderr )) return ak_libakrypt_destroy();


    for( i = 0; i < sizeof(sample_passwords) / sizeof(wchar_t*); i++)
    {
        if ((error = ak_bckey_context_create_kuznechik(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

      /* основная ошибка заключалась в том, что тип wchar_t занимает два байта в памяти,
         а функция wcslen возвращает количестиво символов в строке,
         а не размер памяти, занимаемый строкой

         нижеприведенный код работает верно, поскольку соответствует тому,
         что ожидает функция выработки ключа.

         резюме:
          1. передавайте в функции именно те параметры, что ожидает функция
             (char *, а не wchar_t* )

          2. используйте для кодировки паролей utf8 кодировку
             (так принято для того, чтобы снять проблемы с многобайтными кодировками)

          3. не используйте Windows )))
      */

        if ((error = ak_bckey_context_set_key_from_password(
               &key_from_pwd,                                       /* контекст ключа */
               sample_passwords[i],  /* указатель на область памяти, где живет пароль */
               wcslen(sample_passwords[i])*sizeof(wchar_t), /* размер памяти в байтах */
               sample_salt,                               /* инициализационный вектор */
               wcslen(sample_salt)*sizeof(wchar_t))         /* длина вектора в байтах */
            ) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }

        key_from_pwd.key.unmask(&key_from_pwd.key);

        wprintf(L"for password: %-12ls (length = %2u) ", sample_passwords[i], wcslen(sample_passwords[i]));
        printf("generated key is: ");
        for ( idx = 0; idx < key_from_pwd.bsize; idx++ )
        {
           /* код
               *((ak_uint8*)(key_from_pwd.key.key.data + idx))
              дает неявное приведение к типу ak_pointer */
            printf("%02X ", ((ak_uint8 *)key_from_pwd.key.key.data)[idx] );
        }
        printf("\n");

        if ((error = ak_bckey_context_destroy(&key_from_pwd)) != ak_error_ok)
        {
            ak_libakrypt_destroy();
            return error;
        }
     }
     return ak_libakrypt_destroy();
    }

**Comment by axelkenzo** [comment]
результат работы программы

for password: A            (length =  1) generated key is: FC CB 0C C9 1F A1 4A 59 F8 92 A9 DA FD 8A BE E9
for password: A12          (length =  3) generated key is: FC D1 05 39 BC 58 95 76 1E 4C 7C B9 7F 1E F7 6A
for password: Abcd         (length =  4) generated key is: 2D 27 8C C6 45 93 10 8F 83 AC 57 3A 1A C5 04 88
for password: A321         (length =  4) generated key is: 32 A1 50 88 2E BD 1F 31 F7 90 67 73 48 47 8E E9
for password: BbcdC        (length =  5) generated key is: E8 19 9E 8C 18 F2 28 67 5A F1 AF 52 C2 C3 DD 53
for password: BbcdC12      (length =  7) generated key is: 10 25 30 AD F4 44 37 68 EB 93 DA 0A FF DF E3 CF
for password: BbcdCfgh     (length =  8) generated key is: DC F1 D0 2F 7E A1 B3 AE F4 35 5E EA F2 87 E1 7F
for password: BbcdC321     (length =  8) generated key is: A1 19 75 98 E4 CA 4B 8A B6 93 31 E7 A3 7F 94 DB
for password: DbcdEfghF    (length =  9) generated key is: 38 B3 22 FB 08 7B DB 9A D9 7F 3D 7E F0 C6 B9 48
for password: DbcdEfghF12  (length = 11) generated key is: 22 46 91 60 41 54 E3 72 F3 CD CC 61 A9 56 5C A2
for password: DbcdEfghFijk (length = 12) generated key is: D0 D2 F2 5B 3E C3 30 31 F0 6A 4E 24 C7 BB 67 5C
for password: DbcdEfghF321 (length = 12) generated key is: AE EC FE DF 27 81 0F C7 26 88 E2 9E A3 0D F8 6F

**Comment by george-rudenko** [comment]
Разобрались. Большое спасибо за обратную связь!
