### ISSUE TITLE
Заменить oid magma

### ISSUE THREAD

**Issue by george-rudenko** [axelkenzo/libakrypt-0.x#15]
В файле **ak_oid.c** заменить *oid& магмы:

Строка 122
- с:
   { block_cipher, algorithm, "magma", "1.2.643.2.2.21", NULL, NULL,

- на
   { block_cipher, algorithm, "magma", "1.2.643.7.1.1.5.1", NULL, NULL,

**Comment by axelkenzo** [comment]
Исправлено
