### ISSUE TITLE
Противоречие кода функции с ее описанием.

### ISSUE THREAD

**Issue by anton-sakharov** [axelkenzo/libakrypt-0.x#23]
В файле **_source/ak_bckey.c_** описание параметра out функции **_ak_bckey_context_cmac_** противоречит ее телу.

_Описание параметра:_
out Область памяти, куда будет помещен результат. Память должна быть заранее выделена.
Размер выделяемой памяти должен совпадать с длиной блока используемого алгоритма
блочного шифрования. **Указатель out может принимать значение NULL**.

_Тело функции:_
...
**if( out == NULL ) return ak_error_message( ak_error_null_pointer, __func__,
                                                           "using null pointer to result buffer" );**
...

**Comment by axelkenzo** [comment]
спасибо, в ветке 0.9.х исправлено
