### ISSUE TITLE
Ошибка в функции ak_bckey_decrypt_ctr_hmac.

### ISSUE THREAD

**Issue by anton-sakharov** [axelkenzo/libakrypt-0.x#24]
В файле **source/ak_bckey.c на ветке 0.9** определена функция **ak_bckey_decrypt_ctr_hmac**. 
В ней замечена ошибка при выработке имитовставки, а именно - **на 1224 строке** вызывается функция **ak_hmac_finalize**. Ей на вход передается аргумент **in**, который содержит указатель на зашифрованные данные.
Получается, что имитовставка вычисляется от ассоциированных данных и зашифрованных данных, что противоречит функции **ak_bckey_encrypt_ctr_hmac**, где имитовставка вычисляется от ассоциированных данных и НЕзашифрованных данных. Из-за этого **ak_bckey_decrypt_ctr_hmac** возвращает ошибку **ak_error_not_equal_data**.

P.S. 
1. Если в качестве параметра **out** передать тоже значение, что и для параметра **in**, то функция отработает корректно.
2. Данная ошибка замечена на кормите **804b275**.

Для решения проблемы необходимо заменить в вызове функции **ak_hmac_finalize** аргумент **in** на **out**.

**Comment by axelkenzo** [comment]
Спасибо, исправлено!
